name: Main Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    
        - name: Lighthouse Check
            uses: foo-software/lighthouse-check-action@master
            id: lighthouseCheck
            with:
            outputDirectory: /tmp/artifacts
            urls: "https://felipeffr.github.io/Receitas/"
            device: "all"